msgid ""
msgstr ""
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: bad-memories\n"
"X-Crowdin-Project-ID: 507994\n"
"X-Crowdin-Language: it\n"
"X-Crowdin-File: /main/game/tl/crowdin/options.po\n"
"X-Crowdin-File-ID: 3574\n"
"Project-Id-Version: bad-memories\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Language-Team: Italian\n"
"Language: it_IT\n"
"PO-Revision-Date: 2022-04-04 01:57\n"

# TODO: Translation updated at 2022-04-03 HH:HH# XXtranslate crowdin strings:XX# XX## game/options.rpy:15
msgid "[mschoice] Bad Memories"
msgstr "[mschoice] Memorie errate"

# XX## game/options.rpy:32
msgid "[mschoice] {size=+50}{font=SCRIPTIN.ttf}Bad Memories{/font}{/size}\n\n"
"by recreation\n\n\n\n"
"Every asset used in, or for the images in this game is either paid or created by me and rendered with Daz3D.\n\n\n\n"
"Story by recreation\n\n"
"Images by recreation\n\n"
"Coding: recreation\n\n"
"Music: recreation\n\n"
"SFX: freesound.org\n\n\n\n"
"A big {b}thank you{/b} to everyone who helped me in one or the other way and especially to my Supporter on {a=https://www.patreon.com/bmgames}patreon{/a} and {a=https://subscribestar.adult/bm-games}subscribestar{/a}!!\n\n"
"If you want to find me or more info about the game have a look at {a=https://www.f95zone.to/}{b}f95zone{/b}{/a} or visit my {a=https://bm-rec.itch.io/}{b}itch.io{/b}{/a} page ;)"
msgstr "[mschoice] {size=+50}{font=SCRIPTIN. tf}Bad Memories{/font}{/size}\n\n"
"per ricreazione\n\n\n\n"
"Ogni asset utilizzato in, o per le immagini in questo gioco è pagato o creato da me e renderizzato con Daz3D.\n\n\n\n"
"Storia per ricreazione\n\n"
"Immagini per ricreazione\n\n"
"Coding: ricreazione\n\n"
"Musica: ricreazione\n\n"
"SFX: freesound. rg\n\n\n\n"
"Un grande {b}grazie{/b} a tutti coloro che mi hanno aiutato in un modo o nell'altro e soprattutto al mio Sostenitore su {a=https://www. atreon.com/bmgames}patreon{/a} e {a=https://subscribestar. dult/bm-games}subscribestar{/a}!!\n\n"
"Se vuoi trovarmi o maggiori informazioni sul gioco dai un'occhiata a {a=https://www. 95zone.to/}{b}f95zone{/b}{/a} o visita il mio {a=https://bm-rec.itch.io/}{b}itch.io{/b}{/a} pagina ;)"

