msgid ""
msgstr ""
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Crowdin-Project: bad-memories\n"
"X-Crowdin-Project-ID: 507994\n"
"X-Crowdin-Language: fr\n"
"X-Crowdin-File: /main/game/tl/crowdin/options.po\n"
"X-Crowdin-File-ID: 3574\n"
"Project-Id-Version: bad-memories\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Language-Team: French\n"
"Language: fr_FR\n"
"PO-Revision-Date: 2022-04-15 02:44\n"

# TODO: Translation updated at 2022-04-03 HH:HH# XXtranslate crowdin strings:XX# XX## game/options.rpy:15
msgid "[mschoice] Bad Memories"
msgstr "[mschoice] Mauvais souvenirs"

# XX## game/options.rpy:32
msgid "[mschoice] {size=+50}{font=SCRIPTIN.ttf}Bad Memories{/font}{/size}\n\n"
"by recreation\n\n\n\n"
"Every asset used in, or for the images in this game is either paid or created by me and rendered with Daz3D.\n\n\n\n"
"Story by recreation\n\n"
"Images by recreation\n\n"
"Coding: recreation\n\n"
"Music: recreation\n\n"
"SFX: freesound.org\n\n\n\n"
"A big {b}thank you{/b} to everyone who helped me in one or the other way and especially to my Supporter on {a=https://www.patreon.com/bmgames}patreon{/a} and {a=https://subscribestar.adult/bm-games}subscribestar{/a}!!\n\n"
"If you want to find me or more info about the game have a look at {a=https://www.f95zone.to/}{b}f95zone{/b}{/a} or visit my {a=https://bm-rec.itch.io/}{b}itch.io{/b}{/a} page ;)"
msgstr "[mschoice] {size= 50}{font=SCRIPTIN.ttf}Mauvais souvenirs{/font}{/size}\n\n"
"par recreation\n\n\n\n"
"Chaque objet utilisé dans, ou pour les images de ce jeu est soit payé, soit créé par moi et rendu avec Daz3D.\n\n\n\n"
"Histoire par recreation\n\n"
"Images par recreation\n\n"
"Codage : recreation\n\n"
"Musique : recreation\n\n"
"SFX : freesound.org\n\n\n\n"
"Un grand {b}merci{/b} à tous ceux qui m'ont aidé d'une manière ou d'une autre et surtout à mes Supporters sur {a=https://www.patreon.com/bmgames}patreon{/a} et {a=https://subscribestar.adult/bm-games}subscribestar{/a}!!\n\n"
"Si vous voulez me trouver ou avoir plus d'infos sur le jeu, jetez un coup d'œil à {a=https://www.f95zone.to/}{b}f95zone{/b}{/a} ou visitez ma {a=https://bm-rec.itch.io/}{b}itch.io{/b}{/a} page ;)"

